/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package feedtheneed;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

/**
 *
 * @author Manal Kiyani
 */
public class Chat extends javax.swing.JFrame {

    /**
     * Creates new form Chat
     */
    
     DefaultListModel dm1=new DefaultListModel();
      DefaultListModel dm2=new DefaultListModel();
     
    public Chat() {
        initComponents();
         this.bindData();
    }
private ArrayList getReceivedMsg()
{
    ArrayList<String> receivedmsg=new ArrayList<String>(5);
     try {
                        Class.forName ("oracle.jdbc.OracleDriver");
			Connection con =DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe","HR","HR");
			
			
			PreparedStatement pstmt =con.prepareStatement("select * from chat where sender='donor' ");
			ResultSet rs=pstmt.executeQuery();
                        
			if (rs.next())
                        {
                           String msg= rs.getDate(1)+"\n" +rs.getString(2);
                           receivedmsg.add(msg);
                        }
                       return receivedmsg;
                        
			
		}
		
		catch (Exception e)
		{	
			System.out.println(e.toString());
		}
     return receivedmsg;
}

private ArrayList getSentMsg()
{
    ArrayList<String> sentmsg=new ArrayList<String>(5);
     try {
                        Class.forName ("oracle.jdbc.OracleDriver");
			Connection con =DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe","HR","HR");
			
			
			PreparedStatement pstmt =con.prepareStatement("select * from chat where sender='charity' ");
			ResultSet rs=pstmt.executeQuery();
                        
			while (rs.next())
                        {
                           String msg= rs.getDate(1)+":  " +rs.getString(2);
                           sentmsg.add(msg);
                            System.out.println("in db");
                        }
                       return sentmsg;
                        
			
		}
		
		catch (Exception e)
		{	
			System.out.println(e.toString());
		}
     return sentmsg;
}

private void sendmsg()
{
    String message=msg.getText();
      try {
                        Class.forName ("oracle.jdbc.OracleDriver");
			Connection con =DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe","HR","HR");
			
			
			PreparedStatement pstmt =con.prepareStatement("insert into chat values (SYSDATE,?,'charity',1,1) ");
                        pstmt.setString(1, message);
			ResultSet rs=pstmt.executeQuery();
                        
			if (rs.next())
                        {
                           JOptionPane.showMessageDialog(null,"Message Sent");
                        }
                      
                        
			
		}
		
		catch (Exception e)
		{	
			System.out.println(e.toString());
		}
    
}
private boolean validateMesage()
{
    String message=msg.getText();
    if (message.equals(""))
    {
        JOptionPane.showMessageDialog(null,"Please Enter Message");
        return false;
    }
    else 
    {
        
        return true;
        
}

}

private void bindData()
{
   
    ArrayList<String> rmsg=getReceivedMsg();
    for (String m:rmsg)
    {
        dm1.addElement(m);
    }
    list1.setModel(dm1);
    list1.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    
    
     ArrayList<String> smsg=getSentMsg();
    for (String m:smsg)
    {
        dm2.addElement(m);
    }
    list2.setModel(dm2);
    list2.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    
    
}
private void addMsg()
{
    
      DefaultListModel dm3=new DefaultListModel();
     ArrayList<String> smsg=getSentMsg();
    for (String m:smsg)
    {
        dm3.addElement(m);
    }
    list2.setModel(dm3);
    
    
    
}
        
    /**
     * 
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        msg = new javax.swing.JTextField();
        send = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        list2 = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        list1 = new javax.swing.JList<>();
        back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(247, 164, 166));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/feedtheneed/images/chat_2.png"))); // NOI18N
        jLabel1.setText("Chat");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 0, 150, 80));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 80));

        msg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                msgActionPerformed(evt);
            }
        });
        jPanel1.add(msg, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 230, 30));

        send.setBackground(new java.awt.Color(247, 164, 166));
        send.setForeground(new java.awt.Color(255, 255, 255));
        send.setText("SEND");
        send.setBorder(null);
        send.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendActionPerformed(evt);
            }
        });
        jPanel1.add(send, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 440, 60, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/feedtheneed/images/donor.png"))); // NOI18N
        jLabel2.setText("JoeDoe Foundation");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 290, 60));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/feedtheneed/images/rcv.png"))); // NOI18N
        jLabel3.setText("Josh Bakery");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 210, 60));

        jScrollPane1.setViewportView(list2);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 290, 110));

        jScrollPane4.setViewportView(list1);

        jPanel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 290, 110));

        back.setBackground(new java.awt.Color(247, 164, 166));
        back.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        back.setForeground(new java.awt.Color(255, 255, 255));
        back.setText("Back");
        back.setBorder(null);
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel1.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 480, 120, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        
         CharityDashboard CD=new CharityDashboard();
                            CD.setVisible(true);
                            this.dispose();
    }//GEN-LAST:event_backActionPerformed

    private void msgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_msgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_msgActionPerformed

    private void sendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendActionPerformed
        // TODO add your handling code here:
        
        if (validateMesage())
        {
            sendmsg();
            
            addMsg();
        }
        msg.setText("");
    }//GEN-LAST:event_sendActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Chat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Chat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Chat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Chat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Chat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JList<String> list1;
    private javax.swing.JList<String> list2;
    private javax.swing.JTextField msg;
    private javax.swing.JButton send;
    // End of variables declaration//GEN-END:variables
}
