/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package feedtheneed;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Manal Kiyani
 */
public class requests extends javax.swing.JFrame {

    /**
     * Creates new form requests
     */
    public requests() {
        initComponents();
    }
    private boolean validation()
    {
        if (locationArea.getText().equals("")|| descArea.getText().equals(""))
        {
            JOptionPane.showMessageDialog(new JFrame(), "Please Fill all the fields");
            return false;
            
        }
        else
            return true;
    }
    
 private void insertValues(String location,String desc,String foodtype)
 {
      try {
                        Class.forName ("oracle.jdbc.OracleDriver");
			Connection con =DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe","HR","HR");
			
			
			PreparedStatement pstmt =con.prepareStatement("insert into requests values ('JoeDoe',?,?,?,SYSDATE,SYSDATE,1)");
                      
                        // put values in fields
                        pstmt.setString(1,location);
                        pstmt.setString(2,desc);
                        pstmt.setString(3,foodtype);
                         
                        
                      
			ResultSet rs=pstmt.executeQuery();
                        
			if (rs.next())
                        {
                            JOptionPane.showMessageDialog(new JFrame(), "Request Sent successfully");
                           
                        }
                        else
                        {
                            JOptionPane.showMessageDialog(new JFrame(), "Please Enter Valid Data");
                        }
                        
			
		}
		
		catch (Exception e)
		{	
			System.out.println(e.toString());
		}
 }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtdesc = new javax.swing.JLabel();
        txtfoodtype = new javax.swing.JLabel();
        txtlocation = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        descArea = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        locationArea = new javax.swing.JTextArea();
        foodCombo = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(247, 164, 166));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/feedtheneed/images/admin.png"))); // NOI18N
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("JOE DOE");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("HELLO");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 80));

        txtdesc.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtdesc.setText("Description");
        jPanel1.add(txtdesc, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, -1, -1));

        txtfoodtype.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtfoodtype.setText("Food Type");
        jPanel1.add(txtfoodtype, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        txtlocation.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtlocation.setText("Location");
        jPanel1.add(txtlocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        descArea.setColumns(20);
        descArea.setRows(5);
        jScrollPane1.setViewportView(descArea);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 270, 40));

        locationArea.setColumns(20);
        locationArea.setRows(5);
        jScrollPane2.setViewportView(locationArea);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 270, 40));

        foodCombo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        foodCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Meat", "Fruits", "Vegetable", "Fast Food" }));
        jPanel1.add(foodCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 270, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/feedtheneed/images/Screenshot 2021-06-08 043636.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 280, 120));

        jButton1.setBackground(new java.awt.Color(247, 164, 166));
        jButton1.setText("Send Request");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1KeyPressed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 470, 130, 40));

        jButton2.setBackground(new java.awt.Color(247, 164, 166));
        jButton2.setText("Back");
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, 130, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 521, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1KeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       if (validation())
       {
           String location=locationArea.getText();
           String desc=descArea.getText();
           String type=foodCombo.getSelectedItem().toString();
           insertValues(location,desc,type);
       }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         CharityDashboard CD=new CharityDashboard();
                            CD.setVisible(true);
                            this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(requests.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(requests.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(requests.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(requests.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new requests().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea descArea;
    private javax.swing.JComboBox<String> foodCombo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea locationArea;
    private javax.swing.JLabel txtdesc;
    private javax.swing.JLabel txtfoodtype;
    private javax.swing.JLabel txtlocation;
    // End of variables declaration//GEN-END:variables
}
